name: Build interop Docker image
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  interop:
    runs-on: ${{ fromJSON(vars['DOCKER_RUNNER_UBUNTU'] || '"ubuntu-latest"') }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: set tag name
        id: tag
        # Tagged releases won't be picked up by the interop runner automatically,
        # but they can be useful when debugging regressions.
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" | tee -a $GITHUB_OUTPUT;
            echo "gitref=${GITHUB_REF#refs/tags/}" | tee -a $GITHUB_OUTPUT;
          else
            echo 'tag=latest' | tee -a $GITHUB_OUTPUT;
            echo 'gitref=${{ github.sha }}' | tee -a $GITHUB_OUTPUT;
          fi
      - uses: docker/build-push-action@v4
        id: docker_build_and_push
        with:
          context: "{{defaultContext}}:interop"
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            GITREF=${{ steps.tag.outputs.gitref }}
          tags: martenseemann/quic-go-interop:${{ steps.tag.outputs.tag }}
      - name: Run QUIC Interop tests
        # TODO: Replace once https://github.com/quic-interop/quic-interop-runner/pull/356 is merged.
        uses: mxinden/quic-interop-runner@action
        with:
          name: 'quic-go-latest'
          image: ${{ steps.docker_build_and_push.outputs.imageID }}
          url: https://github.com/quic-go/quic-go
          client: quic-go-latest,quic-go,ngtcp2,neqo,msquic
          server: quic-go-latest,quic-go,ngtcp2,neqo,msquic
